services:
    postgres:
        image: postgres:17.5
        container_name: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: skillwave
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    backend-prod:
        build:
            context: ./backend/
            dockerfile: Dockerfile.prod
            args:
                - DATABASE_URL=postgresql://postgres:password@postgres:5432/skillwave
        container_name: backend-prod
        restart: on-failure
        environment:
            - PORT=3001
        env_file:
            - ./backend/.env.local
        ports:
            - "3001:3001"
            - "4983:4983"
        depends_on:
            postgres:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:3001/ || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    pgdata:
