FROM oven/bun:1.3.1-alpine

WORKDIR /app

# Provide dummy DATABASE_URL for generate (doesn't actually connect)
ENV DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy

# Install dependencies
COPY package.json bun.lock ./
RUN bun install

RUN apk add --no-cache curl

# Copy source code
COPY . .

RUN bun db:generate

EXPOSE 3001

# Start the app in production mode
CMD ["./start.sh"]
