FROM oven/bun:1.3.1-alpine

WORKDIR /app

# Accept build argument for DATABASE_URL
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

# Install dependencies
COPY package.json bun.lock ./
RUN bun install

RUN apk add --no-cache curl

# Copy source code
COPY . .

RUN bun db:generate

EXPOSE 3001

# Start the app in production mode
# CMD ["bun", "prod"]
CMD ["./start.sh"]
